#! /bin/bash

target_ip=${1}
name=${2}
version=${3}
port=${4}
password=${5}

if [[ -z ${target_ip} || -z ${name} || -z ${version} || -z ${port} || -z ${password} ]]
then
    echo
    echo -e "[  \e[1;31m!!!\e[0m  ]   Error! Arguments missing!"
    echo
    echo "Usage example: ./createWorkstation target_ip_addr Identifier xfce 5901 Password"
    echo
    exit 1
fi

subnet=`ssh -i ./ssh_key/bot_rsa bot@$target_ip "ip address | grep tun0 -A2 | grep \"inet \"" | awk '{print $2}'`
ssh -i ./ssh_key/bot_rsa bot@$target_ip "sudo docker run -dt --user $(id -u):$(id -g) -p $subnet:$port:5901 -e VNC_PW=$password --name $name studentvnc$version"
