#!/bin/bash

#ansible-playbook -vv -i ./hosts -t elk ManageUser.yml
#mv ./ovpn_users/elastic.ovpn ./roles/ElasticServer/files/
#mv ./ovpn_users/logstash.ovpn ./roles/LogStashServer/files/logstash.ovpn
#mv ./ovpn_users/kibana.ovpn ./roles/KibanaServer/files/
ansible-playbook -i ./hosts SetupLogService.yml
