#!/bin/bash

docker run -dt -p ${1}:9200:9200 -p ${1}:9300:9300 \
-e "discovery.type=single-node" -e "bootstrap.memory_lock=true" \
-e "ES_JAVA_OPTS=-Xms200m -Xmx500m" -e "cluster.routing.allocation.disk.threshold_enabled=false" \
-v ~/setup_files/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml \
elasticsearch:7.16.2


