#! /bin/bash

if [[ -z ${1} ]]
then
    echo
    echo -e "[  \e[0;31m!!!\e[0m  ]   Error! Arguments missing!"
    echo
    echo "Usage example: destroyWorkstation Identifier"
    echo
    exit 1
fi

docker kill ${1}
docker rm ${1}
