#!/usr/bin/expect -f
set timeout -1
set name [lindex $argv 0]
set openvpn_master_password [lindex $argv 1]
spawn ~/scripts/addVPNUser.sh $name
match_max 100000
expect -exact "\r
Enter pass phrase for /etc/openvpn/pki/private/ca.key:"
send -- "${openvpn_master_password}\r"
expect eof
