#!/usr/bin/expect -f
set timeout -1
set openvpn_master_password [lindex $argv 0]
spawn /scripts/setupVPN.sh
log_file ExpectSetupVPN.log
match_max 100000
expect -exact "\r
Enter New CA Key Passphrase: "
send -- "${openvpn_master_password}\r"
expect -exact "\r
Re-Enter New CA Key Passphrase: "
send -- "${openvpn_master_password}\r"
expect -exact "\r
Common Name (eg: your user, host, or server name) \[Easy-RSA CA\]:"
send -- "ubuntu\r"
expect -exact "\r
Enter pass phrase for /etc/openvpn/pki/private/ca.key:"
send -- "${openvpn_master_password}\r"
expect -exact "\r
Enter pass phrase for /etc/openvpn/pki/private/ca.key:"
send -- "${openvpn_master_password}\r"
expect eof
