#!/bin/bash

target=`find /media -name "*.ovpn"`
for vpn in $target
do
	if [[ "$vpn" == *".ovpn"* ]]
	then
		echo "Would you like to use ${vpn}.(yes/no)"
		read choise
		if [[ $choise == "yes" ]]
		then
			file=`find /media -name $(echo $vpn | awk -F "/" '{print $NF}')`
			openvpn --config "${file}"
			exit 0
		fi
	fi
done
echo "End of executing script"
